import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './base-page';
import { step } from '../decorators/test-step';

/**
 * Invoice Page Object
 * Handles all interactions with the Invoice Management page
 */
export class InvoicePage extends BasePage {
  // Invoice-specific locators
  readonly invoiceNumberInput: Locator;
  readonly clientNameInput: Locator;
  readonly clientEmailInput: Locator;
  readonly invoiceAmountInput: Locator;
  readonly invoiceDescriptionInput: Locator;
  readonly dueDateInput: Locator;
  readonly notesInput: Locator;
  readonly statusDropdown: Locator;
  readonly saveInvoiceButton: Locator;
  readonly deleteButton: Locator;
  readonly confirmDeleteButton: Locator;
  readonly editInvoiceHeading: Locator;

  constructor(page: Page) {
    super(page);

    // Initialize invoice-specific locators
    this.invoiceNumberInput = page.getByRole('textbox', { name: /Invoice Number/i });
    this.clientNameInput = page.getByRole('textbox', { name: /Client Name/i });
    this.clientEmailInput = page.getByRole('textbox', { name: /Client Email/i });
    this.invoiceAmountInput = page.getByRole('spinbutton', { name: /Amount/i });
    this.invoiceDescriptionInput = page.getByRole('textbox', { name: /Description/i });
    this.dueDateInput = page.getByRole('textbox', { name: /Due Date/i });
    this.notesInput = page.getByRole('textbox', { name: /Notes/i });
    this.statusDropdown = page.getByLabel('Status');
    this.saveInvoiceButton = page.getByRole('button', { name: /Create Invoice|Update Invoice|Save/i });
    this.deleteButton = page.getByRole('button', { name: 'Delete' });
    this.confirmDeleteButton = page.getByRole('button', { name: 'Confirm' });
    this.editInvoiceHeading = page.getByText('Edit Invoice');
  }

  @step
  async navigate() {
    await this.gotoInvoices();
  }

  @step
  async fillInvoiceNumber(invoiceNumber: string) {
    await this.invoiceNumberInput.fill(invoiceNumber);
  }

  @step
  async fillClientName(clientName: string) {
    await this.clientNameInput.fill(clientName);
  }

  @step
  async fillClientEmail(email: string) {
    await this.clientEmailInput.fill(email);
  }

  @step
  async fillInvoiceAmount(amount: string) {
    await this.invoiceAmountInput.fill(amount);
  }

  @step
  async fillInvoiceDescription(description: string) {
    await this.invoiceDescriptionInput.fill(description);
  }

  @step
  async fillDueDate(dueDate: string) {
    await this.dueDateInput.fill(dueDate);
  }

  @step
  async fillNotes(notes: string) {
    await this.notesInput.fill(notes);
  }

  @step
  async submitInvoice() {
    await this.createInvoiceButton.click();
  }

  @step
  async createCompleteInvoice(
    invoiceNumber: string,
    clientName: string,
    email: string,
    amount: string,
    description: string,
    dueDate: string,
    notes: string
  ) {
    await this.fillInvoiceNumber(invoiceNumber);
    await this.fillClientName(clientName);
    await this.fillClientEmail(email);
    await this.fillInvoiceAmount(amount);
    await this.fillInvoiceDescription(description);
    await this.fillDueDate(dueDate);
    await this.fillNotes(notes);
    await this.submitInvoice();
  }

  @step
  async verifyInvoiceInList(
    invoiceNumber: string,
    clientName: string,
    description: string,
    amount: string,
    status: string
  ) {
    await expect(this.page.getByRole('heading', { name: invoiceNumber, level: 3 })).toBeVisible();
    await expect(this.page.getByText(clientName)).toBeVisible();
    await expect(this.page.getByText(description)).toBeVisible();
    await expect(this.page.getByText(`Amount: ${amount}`).first()).toBeVisible();
    await expect(this.page.getByText(status).first()).toBeVisible();
  }

  @step
  async createInvoiceWithAutoNumber(
    clientName: string,
    amount: string,
    description: string,
    dueDate: string
  ) {
    await this.fillClientName(clientName);
    await this.fillInvoiceAmount(amount);
    await this.fillInvoiceDescription(description);
    await this.fillDueDate(dueDate);
    await this.submitInvoice();
  }

  @step
  async createBasicInvoice(
    clientName: string,
    amount: string,
    description: string,
    dueDate: string,
    status?: string
  ) {
    await this.fillClientName(clientName);
    await this.fillInvoiceAmount(amount);
    await this.fillInvoiceDescription(description);
    await this.fillDueDate(dueDate);
    if (status) {
      await this.statusDropdown.selectOption([status]);
    }
    await this.submitInvoice();
  }

  @step
  async verifyAutoGeneratedInvoiceNumber(clientName: string) {
    await expect(this.page.getByText(clientName)).toBeVisible();
    await expect(this.page.getByText(/INV-\d+-[A-Z0-9]+/).first()).toBeVisible();
  }

  @step
  async clickEditButtonForInvoice(invoiceNumber: string) {
    await this.page.getByRole('heading', { name: invoiceNumber }).click();
  }

  @step
  async verifyEditFormOpened() {
    await expect(this.editInvoiceHeading).toBeVisible();
  }

  @step
  async clickEditButton() {
    await this.page.getByRole('button', { name: 'Edit' }).first().click();
  }

  @step
  async clickUpdateInvoiceButton() {
    await this.page.getByRole('button', { name: 'Update Invoice' }).click();
  }

  @step
  async updateInvoiceDescription(newDescription: string) {
    const descField = this.invoiceDescriptionInput;
    await descField.clear();
    await descField.fill(newDescription);
  }

  @step
  async updateInvoiceStatus(status: string) {
    await this.statusDropdown.selectOption([status]);
  }

  @step
  async updateInvoiceAmount(amount: string) {
    const amountField = this.invoiceAmountInput;
    await amountField.clear();
    await amountField.fill(amount);
  }

  @step
  async saveInvoiceChanges() {
    await this.saveInvoiceButton.click();
  }

  @step
  async editInvoice(description: string, status: string, amount: string) {
    await this.verifyEditFormOpened();
    await this.updateInvoiceDescription(description);
    await this.updateInvoiceStatus(status);
    await this.updateInvoiceAmount(amount);
    await this.saveInvoiceChanges();
  }

  @step
  async clickDeleteButton() {
    await this.deleteButton.click();
  }

  @step
  async confirmDeletion() {
    await this.confirmDeleteButton.click();
  }

  @step
  async deleteInvoice() {
    await this.clickDeleteButton();
    await this.confirmDeletion();
  }

  @step
  async filterByStatus(status: string) {
    // Use label to select option (more reliable than value)
    await this.page.getByRole('combobox').nth(1).selectOption({ label: status });
  }

  @step
  async clearStatusFilter() {
    await this.page.getByRole('combobox').nth(1).selectOption(['']);
  }

  @step
  async verifyFilteredInvoices(status: string) {
    await expect(this.page.getByText(new RegExp(status, 'i')).first()).toBeVisible();
  }

  @step
  async verifyInvoiceNotInList(invoiceNumber: string) {
    await expect(this.page.getByRole('heading', { name: invoiceNumber, level: 3 })).not.toBeVisible();
  }
}
